USE CoderHouse

--1)SELECCIONAR NOMBRE Y APELLIDO Y FILTRAR Y OBTENER EL NOMBRE SOLO CUANDO ES 'MARK'
Select Nombre, Apellido
FROM Estudiantes
WHERE Nombre = 'Mark'

--2)CANTIDAD DE REGISTROS DENTRO DE LA TABLA ESTUDIANTES
SELECT COUNT (EstudiantesID) as [Cantidad de registros]
FROM Estudiantes

--3)TRAER LOS PRIMEROS 10 REGISTROS DE LA TABLA ASIGNATURAS CUANDO EL COSTO SEA MAYOR A 7.000
SELECT TOP(10) Costo
FROM Asignaturas
WHERE Costo > 7.000

--4)TRAER LOS REGISTROS DE LA TABLA ESTUDAINTES DONDE LOS APELLIDOS EMPIECEN CON LA LETRA M
SELECT Apellido
FROM Estudiantes
WHERE Apellido LIKE 'M%'

--5)EL PROMEDIO DE COSTO DE LOS CURSOS Y CARRERAS CON LAS QUE CUENTA CODERHOUSE DONDE COSTO SEA MAYOR A 6.000
SELECT AVG (Costo) as [Promedio de costo]
FROM Asignaturas
WHERE Costo>6.000 

--6)CUANTAS PROFESIONES HAY REGISTRADAS EN LA TABLA PROFESIONES
SELECT COUNT(DISTINCT(Profesiones)) as Profesiones
FROM Profesiones


